# Generated by Django 3.2.12 on 2022-10-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squadlinkusermodel',
            name='friends',
        ),
        migrations.AddField(
            model_name='squadlinkusermodel',
            name='game',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='squadlinkusermodel',
            name='rank',
            field=models.CharField(default='', max_length=100),
        ),
    ]
