# Generated by Django 3.2.12 on 2022-10-09 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0004_auto_20221007_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squadlinkusermodel',
            old_name='regions',
            new_name='region',
        ),
    ]
