# Generated by Django 4.0.3 on 2022-10-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0005_rename_regions_squadlinkusermodel_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadlinkusermodel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
