# Generated by Django 4.1.1 on 2022-11-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0006_alter_squadlinkusermodel_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadlinkusermodel',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to='UserProfile.squadlinkusermodel'),
        ),
        migrations.AddField(
            model_name='squadlinkusermodel',
            name='requests_received',
            field=models.ManyToManyField(blank=True, null=True, to='UserProfile.squadlinkusermodel'),
        ),
        migrations.AddField(
            model_name='squadlinkusermodel',
            name='requests_sent',
            field=models.ManyToManyField(blank=True, null=True, to='UserProfile.squadlinkusermodel'),
        ),
    ]
